
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - zenyth-network

  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    networks:
      - zenyth-network
    dns:
      - 1.1.1.1
      - 8.8.8.8

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - zenyth-network
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  zenyth-network:
    driver: bridge